name: news
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  #lazy_load_scrollview: ^1.3.0
  path_provider: ^0.4.1
  rxdart: ^0.18.0
  sqflite: ^1.3.0
  json_serializable: ^3.5.1
  overflow_view: 0.3.1
  assorted_layout_widgets: 5.0.0
  chips_choice: 2.0.1
  flutter_bloc: ^7.0.1
  focused_menu: ^1.0.1
  auto_size_text: ^2.1.0
  provider: ^5.0.0
  material_floating_search_bar: ^0.3.4
  implicitly_animated_reorderable_list: ^0.4.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/banner.png
    - images/poster.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/ellie.png
    - images/eric.png
    - images/jenny.png
    - images/kevin.png
    - images/louis.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
